// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUVV53z43qmZDLqR1DpdtVHzFokm0mEzU',
    appId: '1:385824372941:android:1c56bcfd0a609ace549184',
    messagingSenderId: '385824372941',
    projectId: 'b2c-ximply-test',
    databaseURL: 'https://b2c-ximply-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'b2c-ximply-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiuEJaCAv6F-Rl624nvwb9jBLEHMLLYF4',
    appId: '1:385824372941:ios:1589a5043a69d025549184',
    messagingSenderId: '385824372941',
    projectId: 'b2c-ximply-test',
    databaseURL: 'https://b2c-ximply-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'b2c-ximply-test.appspot.com',
    iosClientId: '385824372941-lrer6m1vtk31nm6psnkfm0nnoftfs90g.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );
}
